services:
  app:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-customer_db}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    networks:
      - customer-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-customer_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - customer-network

networks:
  customer-network:
    driver: bridge

volumes:
  postgres-data:
